/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.10
 * Generated at: 2021-09-30 10:34:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.resource.doctorRegistration;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class doctorRegistration_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css\" integrity=\"sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU\" crossorigin=\"anonymous\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("@media(max-width:1100px) {\r\n");
      out.write("	.checkbox-inline {\r\n");
      out.write("		display: none;\r\n");
      out.write("	}\r\n");
      out.write("	.checkbox-second {\r\n");
      out.write("		margin-top: 20px\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media(min-width:1100px) {\r\n");
      out.write("	.checkbox-second {\r\n");
      out.write("		display: none\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* Start My Style doctorSignUp */\r\n");
      out.write("\r\n");
      out.write(".login {\r\n");
      out.write("	\r\n");
      out.write("	background-size: cover;\r\n");
      out.write("	/*height: 793px;*/\r\n");
      out.write("	margin-top: 50px;\r\n");
      out.write("  background-color:black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login h2 {\r\n");
      out.write("	color: #feffff;\r\n");
      out.write("	padding-top: 30px;\r\n");
      out.write("	line-height: 100%\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("main {\r\n");
      out.write("	min-width: 450px;\r\n");
      out.write("	margin: 35px auto\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media (max-width:665px) {\r\n");
      out.write("	main {\r\n");
      out.write("		max-width: 480px !important;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media(max-width:563px) {\r\n");
      out.write("	main {\r\n");
      out.write("		max-width: 480px !important;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media(max-width:529px) {\r\n");
      out.write("	main {\r\n");
      out.write("		/* width: 50%; */\r\n");
      out.write("		min-width: 365px;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-container {\r\n");
      out.write("	border: 2px solid #457697;\r\n");
      out.write("	height: auto;\r\n");
      out.write("	background-color: #feffff;\r\n");
      out.write("	min-width: 480px;\r\n");
      out.write("	border-radius: 8px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-container h1 {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	font-size: 25px;\r\n");
      out.write("	color: #2e79b6;\r\n");
      out.write("	padding: 12px 0\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-container form {\r\n");
      out.write("	width: 86%;\r\n");
      out.write("	margin: 1rem auto\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".input-lg {\r\n");
      out.write("	margin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".checkbox-inline,\r\n");
      out.write(".checkbox-second {\r\n");
      out.write("	color: #B8B8B8;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	font-weight: normal;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".checkbox-inline a,\r\n");
      out.write(".checkbox-second a,\r\n");
      out.write(".spanSign a {\r\n");
      out.write("	color: #0886DD\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-container span.bookType,\r\n");
      out.write(".spanSign {\r\n");
      out.write("	color: #B8B8B8;\r\n");
      out.write("	display: block;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	margin-bottom: 10px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".spanRadio {\r\n");
      out.write("	color: #606060\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-container form .or-divider {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	margin: 20px 198px;\r\n");
      out.write("	color: #dcc1c1\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".or-divider::after,\r\n");
      out.write(".or-divider::before {\r\n");
      out.write("	content: \"\";\r\n");
      out.write("	display: block;\r\n");
      out.write("	height: .5rem;\r\n");
      out.write("	width: 44%;\r\n");
      out.write("	border-bottom: 1px solid #cecece;\r\n");
      out.write("	float: left;\r\n");
      out.write("	margin-top: 5px;\r\n");
      out.write("	text-align: center\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".or-divider::before {\r\n");
      out.write("	float: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=submit],\r\n");
      out.write("input[type=submit]:hover {\r\n");
      out.write("	margin-top: 40px;\r\n");
      out.write("	background-color: #05a0f2;\r\n");
      out.write("	color: #c2f3fc\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media(max-width:991px) {\r\n");
      out.write("	input[type=submit] {\r\n");
      out.write("		margin-top: 17px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* End My Style doctorSignUp */\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!--Start: Sign up-->\r\n");
      out.write("	<section class=\"login\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<h2 class=\"text-center\">Doctor Registration</h2>\r\n");
      out.write("			</div>\r\n");
      out.write("			<main>\r\n");
      out.write("				<!-- Start: Form -->\r\n");
      out.write("				<artical>\r\n");
      out.write("					<div class=\"form-container\">\r\n");
      out.write("						\r\n");
      out.write("						<!-- Start: Form -->\r\n");
      out.write("						<form action=\"\">\r\n");
      out.write("							<div class=\"row\">\r\n");
      out.write("								<div class=\"left col-md-6 col-sm-12 col-xs-12\">\r\n");
      out.write("									<input type=\"text\" class=\"form-control input-lg\" id=\"firstName\" placeholder=\"First Name\">\r\n");
      out.write("									<input type=\"text\" class=\"form-control input-lg\" placeholder=\"Last name\">\r\n");
      out.write("									<input type=\"tel\" class=\"form-control input-lg\" placeholder=\"Mobile\">\r\n");
      out.write("									<input type=\"email\" class=\"form-control input-lg\" placeholder=\"Email\">\r\n");
      out.write("									<input type=\"text\" class=\"form-control input-lg\" placeholder=\"City\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"right col-md-6 col-sm-12 col-xs-12\">\r\n");
      out.write("									<input type=\"text\" class=\"form-control input-lg\" id=\"area\" placeholder=\"Education Institute Name\">\r\n");
      out.write("									<input type=\"text\" class=\"form-control input-lg\" placeholder=\"Medical ID\">\r\n");
      out.write("									<input type=\"password\" class=\"form-control input-lg\" placeholder=\"Specialization Area\">\r\n");
      out.write("									<input type=\"password\" class=\"form-control input-lg\" placeholder=\"Digree Name\">\r\n");
      out.write("\r\n");
      out.write("									<label class=\"checkbox-inline\">\r\n");
      out.write("				 						<input type=\"checkbox\"  name=\"remember\" value=\"\"> By signing up you agree<br>to our <a href=\"Terms.html\">terms and condition </a> \r\n");
      out.write("									</label>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"row\">\r\n");
      out.write("								<div class=\"col-md-6\">\r\n");
      out.write("										<label class=\"checkbox-second col-md-6 \">\r\n");
      out.write("				 					<input type=\"checkbox\"  name=\"remember\" value=\"\"> By signing up you agree<br>to our <a href=\"#\">terms and condition </a> \r\n");
      out.write("								</label>\r\n");
      out.write("								</div>\r\n");
      out.write("								\r\n");
      out.write("							\r\n");
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"row\">\r\n");
      out.write("								<div class=\"col-md-3\"></div>\r\n");
      out.write("								<div class=\"col-md-6 text-center\">\r\n");
      out.write("									<input type=\"submit\" class=\"btn btn-primary btn-lg btn-block btn_form  col-sm-12\" value=\"SUBMIT\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"col-md-3\"></div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<br/>\r\n");
      out.write("							<div class=\"text-center or-divider\">or</div>\r\n");
      out.write("							<div class=\"text-center\">\r\n");
      out.write("								<span class=\"spanSign\">Go Back\r\n");
      out.write("								    <a href=\"../../index.jsp\">Home</a><br/>\r\n");
      out.write("								</span>\r\n");
      out.write("							</div>\r\n");
      out.write("						</form>\r\n");
      out.write("					</div>\r\n");
      out.write("				</artical>\r\n");
      out.write("			</main>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<!-- End: Sign up --->\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
