/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.10
 * Generated at: 2021-09-30 03:34:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.resource.medicalSpecialties;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class medicalSpecialties_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./resource/common/css/bootstrap.min.css\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write(".box-item {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	background: #41ead4;\r\n");
      out.write("	border-right:2px solid white;\r\n");
      out.write("	border-bottom:2px solid white;\r\n");
      out.write("	\r\n");
      out.write("	position:absolute;\r\n");
      out.write("	z-index: -8;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box-item h4,.box-item p {\r\n");
      out.write("	color: black;\r\n");
      out.write("	text-align:center;\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write(" .box-item p {\r\n");
      out.write("	color: black;\r\n");
      out.write("	text-align:justify;\r\n");
      out.write("	font-size:18px;\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write(".box-item h4 {\r\n");
      out.write("	font-weight:bolder;\r\n");
      out.write("	padding:5px;\r\n");
      out.write("	font-size:25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h{\r\n");
      out.write("	font-weight:bolder;\r\n");
      out.write("	font-size:50px;\r\n");
      out.write("}\r\n");
      out.write(".box-item p:hover {\r\n");
      out.write("	color: black;\r\n");
      out.write("	text-align:justify;\r\n");
      out.write("	font-size:25px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write(".box-item h4:hover {\r\n");
      out.write("	font-weight:bolder;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media all and (max-width: 300px) {\r\n");
      out.write("	.test h1{\r\n");
      out.write("		font-size:30px;\r\n");
      out.write("		text-align:center;\r\n");
      out.write("		\r\n");
      out.write("		width:100%;\r\n");
      out.write("		height:auto;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media all and (min-width: 300px) {\r\n");
      out.write("	.test h1{\r\n");
      out.write("		font-size:50px;\r\n");
      out.write("		text-align:center;\r\n");
      out.write("		\r\n");
      out.write("		width:100%;\r\n");
      out.write("		height:auto;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container-fluid test\">\r\n");
      out.write("	\r\n");
      out.write("	   <div style=\"width:100%; height:200px;\"></div>\r\n");
      out.write("	   \r\n");
      out.write("		<div class=\"text-center p-5\">\r\n");
      out.write("			<h1>Medical Specialties</h1>\r\n");
      out.write("		</div>\r\n");
      out.write("	\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"box-item col-sm-12 col-md-3 col-xl-3\">\r\n");
      out.write("					<div>\r\n");
      out.write("						<h4 >Heart Care Center</h4>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						<p>Cardiology is a broad field encompassing preventive care,\r\n");
      out.write("							screening, advanced diagnostic tests, invasive and non-invasive\r\n");
      out.write("							procedures, post-operative management, cardiac rehabilitation,\r\n");
      out.write("							and a full range of surgical programmes.</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"box-item col-sm-12 col-md-3 col-xl-3\">\r\n");
      out.write("					<div>\r\n");
      out.write("						<h4>Eye Care Specialist</h4>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						<p>The gift of eyesight is one we aim to restore and improve\r\n");
      out.write("							both in adults and children seeking the expertise of our\r\n");
      out.write("							specialists. Offering a range of eye care services, our team\r\n");
      out.write("							employs world-class diagnostic and surgical equipment, tailoring\r\n");
      out.write("							treatment to your individual needs.</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"box-item col-sm-12 col-md-3 col-xl-3\">\r\n");
      out.write("					<div>\r\n");
      out.write("						<h4>Child Care Center</h4>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						<p>Dedicated to the nurturing care of children, we provide\r\n");
      out.write("							excellence in medical, surgical and rehabilitative care, with\r\n");
      out.write("							paediatricians who are sensitive to childrenâs needs and\r\n");
      out.write("							responsive to parental concerns.</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"box-item col-sm-12 col-md-3 col-xl-3\">\r\n");
      out.write("					<div>\r\n");
      out.write("						<h4>Women's Health</h4>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						<p>ABC Hospital offers a comprehensive range of wellness\r\n");
      out.write("							programmes that provide diagnoses, treatment and support in the\r\n");
      out.write("							areas of health that most impact womenâs lives.</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"box-item col-sm-12 col-md-3 col-xl-3\">\r\n");
      out.write("					<div>\r\n");
      out.write("						<h4>Neurology Specialist</h4>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						<p>ABC Hospital is a regional leader in the complex field\r\n");
      out.write("							of neurology and cutting-edge scientific research. Our skilled\r\n");
      out.write("							neurologists have had enormous success treating patients\r\n");
      out.write("							diagnosed with brain trauma, epilepsy, sleep disorders, strokes,\r\n");
      out.write("							and neck and spine conditions.</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"box-item col-sm-12 col-md-3 col-xl-3\">\r\n");
      out.write("					<div>\r\n");
      out.write("						<h4>Gastroenterology Specialist</h4>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						<p>Our team of highly experienced gastroenterologists is on\r\n");
      out.write("							hand to treat a wide range of digestive conditions. Their focus:\r\n");
      out.write("							achieving an accurate diagnosis the first time, so you can\r\n");
      out.write("							receive the right treatment as soon as possible.</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"box-item col-sm-12 col-md-3 col-xl-3\">\r\n");
      out.write("					<div>\r\n");
      out.write("						<h4>ENT Center</h4>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						<p>Our otorhinolaryngology specialists have a distinguished\r\n");
      out.write("							record of treating a wide range of ear, nose and throat (ENT)\r\n");
      out.write("							conditions, as well as head and neck ailments. It was specialists\r\n");
      out.write("							at ABC Hospital who performed Sri Lankaâs first ever\r\n");
      out.write("							unilateral cochlear transplant, with the assistance of regional\r\n");
      out.write("							experts.</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"box-item col-sm-12 col-md-3 col-xl-3\">\r\n");
      out.write("					<div>\r\n");
      out.write("						<h4>Endocrinology Specialist</h4>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						<p>With expertise in all aspects of endocrinology, our\r\n");
      out.write("							dedicated team offers a total care approach to people with\r\n");
      out.write("							diabetes, providing specialist and personalised guidance that\r\n");
      out.write("							enables the individual to keep their condition under control and\r\n");
      out.write("							lead a normal, healthy life.</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"box-item col-sm-12 col-md-3 col-xl-3\">\r\n");
      out.write("					<div>\r\n");
      out.write("						<h4>General Surgery</h4>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						<p>Our experienced surgical teams bring together a culmination\r\n");
      out.write("							of expertise and treatment care plans across a range of\r\n");
      out.write("							sub-specialties. These expert surgeons have access to some of the\r\n");
      out.write("							regionâs most advanced facilities, including a fully equipped\r\n");
      out.write("							laparoscopic theatre with cutting-edge video system and\r\n");
      out.write("							high-definition display.</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"box-item col-sm-12 col-md-3 col-xl-3\">\r\n");
      out.write("					<div>\r\n");
      out.write("						<h4>Nephrology Specialist</h4>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						<p>We take great care of patients who suffer from problems\r\n");
      out.write("							involving the kidneys or complex blood pressure issues.\r\n");
      out.write("							Comprehensive services for nephrology outpatient and inpatient\r\n");
      out.write("							care as well as renal dialysis services are provided by ABC\r\n");
      out.write("							Hospital</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"box-item col-sm-12 col-md-3 col-xl-3\">\r\n");
      out.write("					<div>\r\n");
      out.write("						<h4>Orthopedics Center</h4>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						<p>ABC Hospital is on par with the best centres in the\r\n");
      out.write("							region when it comes to providing the latest in orthopaedic\r\n");
      out.write("							treatments and orthopaedic surgical advancements.</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"box-item col-sm-12 col-md-3 col-xl-3\">\r\n");
      out.write("					<div>\r\n");
      out.write("						<h4>Urology Specialist</h4>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						<p>In a field that requires expertly honed surgical skills,\r\n");
      out.write("							our urology specialists are among the regionâs top surgeons.\r\n");
      out.write("							Their abilities and experience are enhanced by the world-class\r\n");
      out.write("							technology and equipment available to them at ABC Hospital.</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("	src=\"./resource/common/js/bootstrap.min.js\"></script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
