/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.10
 * Generated at: 2021-09-30 03:34:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.resource.navigation;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class navigation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<!-- Required meta tags -->\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,400,700\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./resource/common/fonts/icomoon/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./resource/common/css/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./resource/common/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./resource/common/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("<title>ABC Hospital</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".container-fluid {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: auto;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".row-1 {\r\n");
      out.write("	background-color: white;\r\n");
      out.write("	color: black;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: auto;\r\n");
      out.write("	position: fixed;\r\n");
      out.write("	z-index: 10;\r\n");
      out.write("	padding-left: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".row-2 {\r\n");
      out.write("	background-color: white;\r\n");
      out.write("	color: black;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: auto;\r\n");
      out.write("	position: fixed;\r\n");
      out.write("	z-index: 10;\r\n");
      out.write("	top: 130px;\r\n");
      out.write("	padding-left: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".row-3 {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: auto;\r\n");
      out.write("	position: fixed;\r\n");
      out.write("	z-index: 10;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"row-1\"\r\n");
      out.write("		style=\"background-color: white; width: 100; height: auto;\">\r\n");
      out.write("		<div class=\"row w-100\">\r\n");
      out.write("			<h4\r\n");
      out.write("				style=\"font-size: 15px; background-color: white; color: black; text-align: left;\">\r\n");
      out.write("				<i class=\"bi bi-telephone-fill\"></i> : +94 76 875 5787 &nbsp <i\r\n");
      out.write("					class=\"bi bi-envelope-fill\"></i> : <a href=\"abchospital@gmail.com \">abchospital@gmail.com\r\n");
      out.write("				</a> <a href=\"https://facebook/abchospital.com\"><i\r\n");
      out.write("					class=\"bi bi-facebook\"> </i> : https://facebook/abchospital.com</a>\r\n");
      out.write("			</h4>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container-fluid row-2\" style=\"background-color: black;\">\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<marquee direction=\"right\">\r\n");
      out.write("				<h3 style=\"color: white; font-style: normal; font-weight: bolder;\">\r\n");
      out.write("					<a\r\n");
      out.write("						style=\"font-size: 15px; border-radius: 3px; background-color: white; color: black; right: 25px; position: relative;\"\r\n");
      out.write("						href=\"#appoinment\">&nbsp Book an Appointment &nbsp </a> <a\r\n");
      out.write("						style=\"font-size: 15px; border-radius: 3px; background-color: #fac748; color: black;\"\r\n");
      out.write("						href=\"#packages\">&nbsp Health Packages &nbsp </a> <a\r\n");
      out.write("						style=\"font-size: 15px; border-radius: 3px; background-color: none; color: white;\">&nbsp\r\n");
      out.write("						Make a payment &nbsp </a> <a\r\n");
      out.write("						style=\"font-size: 15px; border-radius: 3px; background-color: #ff9f1c; color: black;\"\r\n");
      out.write("						href=\"pay.jsp\">&nbsp Pay Online &nbsp </a>\r\n");
      out.write("				</h3>\r\n");
      out.write("			</marquee>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"site-mobile-menu\">\r\n");
      out.write("		<div class=\"site-mobile-menu-header\">\r\n");
      out.write("			<div class=\"site-mobile-menu-close mt-3\">\r\n");
      out.write("				<span class=\"icon-close2 js-menu-toggle\"></span>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"site-mobile-menu-body\"></div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<header class=\"site-navbar row-3\" role=\"banner\"\r\n");
      out.write("		style=\"background-color: black;\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row align-items-center\">\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-11 col-xl-2\">\r\n");
      out.write("					<h1 class=\"mb-0 site-logo\">\r\n");
      out.write("						<a href=\"#home\" class=\"text-white mb-0\"> <span\r\n");
      out.write("							style=\"font-weight: 900; color: yellow;\">ABC</span>\r\n");
      out.write("						</a>\r\n");
      out.write("					</h1>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-12 col-md-10 d-none d-xl-block\">\r\n");
      out.write("					<nav class=\"site-navigation position-relative text-right\"\r\n");
      out.write("						role=\"navigation\">\r\n");
      out.write("						<ul class=\"site-menu js-clone-nav mr-auto d-none d-lg-block\">\r\n");
      out.write("							<li class=\"active\"><a href=\"#home\"><span>Home</span></a></li>\r\n");
      out.write("							<li class=\"has-children\"><a href=\"#ourcenters\"> <span\r\n");
      out.write("									style=\"color: white\">Our Centers</span>\r\n");
      out.write("							</a>\r\n");
      out.write("								<ul class=\"dropdown arrow-top\">\r\n");
      out.write("									<li><a href=\"index.jsp\">Colombo</a></li>\r\n");
      out.write("									<li><a href=\"index.jsp\">Nugegoda</a></li>\r\n");
      out.write("									<li><a href=\"index.jsp\">Aluthgama</a></li>\r\n");
      out.write("									<li><a href=\"index.jsp\">Mathara</a></li>\r\n");
      out.write("									<li><a href=\"index.jsp\">Jaffna</a></li>\r\n");
      out.write("								</ul></li>\r\n");
      out.write("\r\n");
      out.write("							<li class=\"has-children\"><a href=\"#doctors\"><span>Doctors</span></a>\r\n");
      out.write("								<ul class=\"dropdown arrow-top\">\r\n");
      out.write("\r\n");
      out.write("									");

								   for(int i=0; i<=5; i++){
								   
      out.write("<li style=\"width: 300px; height: auto;\"><a href=\"#\"\">Dr. Savindu Pasintha - colombo</a></li>\r\n");
      out.write("									");

								   }
								   
      out.write("\r\n");
      out.write("\r\n");
      out.write("								</ul></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("							<li class=\"has-children\"><a href=\"#packages\"><span>Medical\r\n");
      out.write("										Packages</span></a>\r\n");
      out.write("								<ul class=\"dropdown arrow-top\">\r\n");
      out.write("									<li style=\"width: 100%; height: auto;\">\r\n");
      out.write("										<div style=\"width: 100%; height: auto;\">\r\n");
      out.write("											<table class=\"table table-sm\"\r\n");
      out.write("												style=\"width: 100%; height: auto;\">\r\n");
      out.write("												<thead style=\"border: 1px solid white;\">\r\n");
      out.write("													<tr>\r\n");
      out.write("														<th\r\n");
      out.write("															style=\"color: white; background-color: black; width: 200px; height: 50px; border-right: 1px solid white; border-bottom: 2px solid black; border-left: 2px solid black;\"\r\n");
      out.write("															scope=\"col\">SAREN</th>\r\n");
      out.write("														<th\r\n");
      out.write("															style=\"color: white; background-color: black; width: 200px; height: 50px; border-right: 1px solid white; border-bottom: 2px solid black;\"\r\n");
      out.write("															scope=\"col\">SURGERY</th>\r\n");
      out.write("														<th\r\n");
      out.write("															style=\"color: white; background-color: black; width: 200px; height: 50px; border-right: 1px solid white; border-bottom: 2px solid black;\"\r\n");
      out.write("															scope=\"col\">MATENITY</th>\r\n");
      out.write("														<th\r\n");
      out.write("															style=\"color: white; background-color: black; width: 200px; height: 50px; border-right: 1px solid black; border-bottom: 2px solid black;\"\r\n");
      out.write("															scope=\"col\">RADIOLOGY</th>\r\n");
      out.write("													</tr>\r\n");
      out.write("												</thead>\r\n");
      out.write("												<tbody>\r\n");
      out.write("													");
 for(int x=0; x<5; x++){ 
      out.write("\r\n");
      out.write("													<tr>\r\n");
      out.write("														<td\r\n");
      out.write("															style=\"color: black; background-color: white; width: 25%;\"><p>abc</p></td>\r\n");
      out.write("														<td\r\n");
      out.write("															style=\"color: black; background-color: white; width: 25%;\"><p>abc</p></td>\r\n");
      out.write("														<td\r\n");
      out.write("															style=\"color: black; background-color: white; width: 25%;\"><p>abc</p></td>\r\n");
      out.write("														<td\r\n");
      out.write("															style=\"color: black; background-color: white; width: 25%;\"><p>abc</p></td>\r\n");
      out.write("													</tr>\r\n");
      out.write("													");
} 
      out.write("\r\n");
      out.write("												</tbody>\r\n");
      out.write("											</table>\r\n");
      out.write("										</div>\r\n");
      out.write("									</li>\r\n");
      out.write("								</ul></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("							<li><a href=\"#contact\"><span>Contact us</span></a></li>\r\n");
      out.write("							<li><a href=\"#about\"><span>About us</span></a></li>\r\n");
      out.write("							<li><a href=\"./resource/login/login.jsp\"><span\r\n");
      out.write("									style=\"color: red;\">Login</span></a></li>\r\n");
      out.write("							<li><a href=\"./resource/registration/registration.jsp\"><span\r\n");
      out.write("									style=\"color: red;\">Registartion</span></a></li>\r\n");
      out.write("							<li><a href=\"#cart\"><span><i style=\"color: gold;\"\r\n");
      out.write("										class=\"bi bi-cart3\">cart</i></span></a></li>\r\n");
      out.write("							<li><a href=\"#cart\"><span><i style=\"color: gold;\"\r\n");
      out.write("										class=\"bi bi-arrow-90deg-right\">check out</i></span></a></li>\r\n");
      out.write("							<li><a href=\"#payment\"><span\r\n");
      out.write("									style=\"color: gold; font-size: 15px;\">payment</span></a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</nav>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"d-inline-block d-xl-none ml-md-0 mr-auto py-3\"\r\n");
      out.write("					style=\"position: relative; top: 3px;\">\r\n");
      out.write("					<a href=\"#\" class=\"site-menu-toggle js-menu-toggle text-white\">\r\n");
      out.write("						<span class=\"icon-menu h3\"></span>\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script type=\"text/javascript\"\r\n");
      out.write("		src=\"./resource/common/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\" src=\"./resource/common/js/popper.min.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\"\r\n");
      out.write("		src=\"./resource/common/js/bootstrap.min.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\"\r\n");
      out.write("		src=\"./resource/common/js/jquery.sticky.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\" src=\"./resource/common/js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
