/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.10
 * Generated at: 2021-09-30 03:34:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.resource.appoinment;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class appoinment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");

/*
<link rel="stylesheet" href="../common/css/bootstrap.min.css">

*/

      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".box-rox {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box-row-item {\r\n");
      out.write("	width: 50%;\r\n");
      out.write("	height: auto;\r\n");
      out.write("	background: #e6e6e6;\r\n");
      out.write("	border: 2px solid none;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	left: 25%;\r\n");
      out.write("	right: 25%;\r\n");
      out.write("	padding: 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box-row-item-1 {\r\n");
      out.write("	height: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box-row-item-1 p {\r\n");
      out.write("	color: black;\r\n");
      out.write("	text-align: justify;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box-row-item-1 h4 {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	font-weight: bolder;\r\n");
      out.write("	padding: 5px;\r\n");
      out.write("	color: white;\r\n");
      out.write("	font-size: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box-row-item-1 h1 {\r\n");
      out.write("	font-size: 50px;\r\n");
      out.write("	font-weight: bolder;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media all and (max-width: 300px) {\r\n");
      out.write("	.test h1{\r\n");
      out.write("		font-size:30px;\r\n");
      out.write("		text-align:center;\r\n");
      out.write("		\r\n");
      out.write("		width:100%;\r\n");
      out.write("		height:auto;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media all and (min-width: 300px) {\r\n");
      out.write("	.test h1{\r\n");
      out.write("		font-size:50px;\r\n");
      out.write("		text-align:center;\r\n");
      out.write("		\r\n");
      out.write("		width:100%;\r\n");
      out.write("		height:auto;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container-fluid test\">\r\n");
      out.write("		<div class=\"text-center p-5\">\r\n");
      out.write("			<h1>ABC Hospital</h1>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"box-row\">\r\n");
      out.write("			<div class=\"box-row-item\">\r\n");
      out.write("				<div class=\"bg-primary box-row-item-1\">\r\n");
      out.write("					<h4>Book an Appointment and Save upto Rs.300/=</h4>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<label class=\"text-danger\"> ");
 
				    String validation = "Sorry, the doctor you searched is not available. Please try- Selecting an alternative Hospital :- Selecting an alternative Specialization";
				    if(true){
				    	out.print(validation);
				    }
				    
      out.write("\r\n");
      out.write("					</label>\r\n");
      out.write("\r\n");
      out.write("					<form>\r\n");
      out.write("						<div class=\"mb-3\">\r\n");
      out.write("							<label for=\"exampleFormControlInput1\" class=\"form-label\"></label>\r\n");
      out.write("							<select class=\"form-select  form-control\"\r\n");
      out.write("								aria-label=\"Default select example\">\r\n");
      out.write("								<option selected>Any Doctor</option>\r\n");
      out.write("								<option value=\"1\">One</option>\r\n");
      out.write("								<option value=\"2\">Two</option>\r\n");
      out.write("								<option value=\"3\">Three</option>\r\n");
      out.write("							</select>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"mb-3\">\r\n");
      out.write("							<select class=\"form-select  form-control\"\r\n");
      out.write("								aria-label=\"Default select example\">\r\n");
      out.write("								<option selected>Any Specialization</option>\r\n");
      out.write("								<option value=\"1\">One</option>\r\n");
      out.write("								<option value=\"2\">Two</option>\r\n");
      out.write("								<option value=\"3\">Three</option>\r\n");
      out.write("							</select>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"mb-3\">\r\n");
      out.write("							<select class=\"form-select form-control\"\r\n");
      out.write("								aria-label=\"Default select example\">\r\n");
      out.write("								<option selected>Any Hospital</option>\r\n");
      out.write("								<option value=\"1\">One</option>\r\n");
      out.write("								<option value=\"2\">Two</option>\r\n");
      out.write("								<option value=\"3\">Three</option>\r\n");
      out.write("							</select>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"mb-3\">\r\n");
      out.write("							<input type=\"datetime-local\" class=\"form-control\"\r\n");
      out.write("								id=\"exampleFormControlInput1\" required>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"text-center mb-3\">\r\n");
      out.write("							<button type=\"submit\" class=\"btn btn-dark \">search</button>\r\n");
      out.write("						</div>\r\n");
      out.write("					</form>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
 /*
<script type="text/javascript"
src="../common/js/bootstrap.min.js"></script>
*/ 
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
