/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.10
 * Generated at: 2021-09-30 03:34:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.resource.footer;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap');\r\n");
      out.write("body{\r\n");
      out.write("	line-height: 1.5;\r\n");
      out.write("	font-family: 'Poppins', sans-serif;\r\n");
      out.write("}\r\n");
      out.write("*{\r\n");
      out.write("	margin:0;\r\n");
      out.write("	padding:0;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write(".container{\r\n");
      out.write("	max-width: 1170px;\r\n");
      out.write("	margin:auto;\r\n");
      out.write("}\r\n");
      out.write(".row{\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-wrap: wrap;\r\n");
      out.write("}\r\n");
      out.write("ul{\r\n");
      out.write("	list-style: none;\r\n");
      out.write("}\r\n");
      out.write("li{\r\n");
      out.write("	text-align: justify;\r\n");
      out.write("}\r\n");
      out.write(".footer{\r\n");
      out.write("width:100%;\r\n");
      out.write("    position:relative;\r\n");
      out.write("    top: 65%;\r\n");
      out.write("	background-color: #02091a;\r\n");
      out.write("    padding: 70px 0;\r\n");
      out.write("}\r\n");
      out.write(".footer-col{\r\n");
      out.write("   width: 25%;\r\n");
      out.write("   padding: 0 15px;\r\n");
      out.write("}\r\n");
      out.write(".footer-col h4{\r\n");
      out.write("	font-size: 18px;\r\n");
      out.write("	color: #ffffff;\r\n");
      out.write("	text-transform: capitalize;\r\n");
      out.write("	margin-bottom: 35px;\r\n");
      out.write("	font-weight: 500;\r\n");
      out.write("	position: relative;\r\n");
      out.write("} \r\n");
      out.write(".footer-col ul li:not(:last-child){\r\n");
      out.write("	margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write(".footer-col ul li a{\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	text-transform: capitalize;\r\n");
      out.write("	color: #ffffff;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	font-weight: 300;\r\n");
      out.write("	color: #bbbbbb;\r\n");
      out.write("	display: block;\r\n");
      out.write("	transition: all 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write(".footer-col ul li a:hover{\r\n");
      out.write("	color: #ffffff;\r\n");
      out.write("	padding-left: 8px;\r\n");
      out.write("}\r\n");
      out.write(".footer-col .social-links a{\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	height: 40px;\r\n");
      out.write("	width: 40px;\r\n");
      out.write("	background-color: rgba(255,255,255,0.2);\r\n");
      out.write("	margin:0 10px 10px 0;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	line-height: 40px;\r\n");
      out.write("	border-radius: 50%;\r\n");
      out.write("	color: #ffffff;\r\n");
      out.write("	transition: all 0.5s ease;\r\n");
      out.write("}\r\n");
      out.write(".footer-col .social-links a:hover{\r\n");
      out.write("	color: #24262b;\r\n");
      out.write("	background-color: #ffffff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media(max-width: 767px){\r\n");
      out.write("  .footer-col{\r\n");
      out.write("    width: 50%;\r\n");
      out.write("    margin-bottom: 30px;\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("@media(max-width: 574px){\r\n");
      out.write("  .footer-col{\r\n");
      out.write("    width: 100%;\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("  <footer class=\"footer\">\r\n");
      out.write("  	 <div class=\"container\">\r\n");
      out.write("  	 	<div class=\"row\">\r\n");
      out.write("  	 		<div class=\"footer-col\">\r\n");
      out.write("  	 			<h4>ABC HOSPITAL</h4>\r\n");
      out.write("  	 			<ul>\r\n");
      out.write("  	 				<li><a href=\"#home\">Home</a></li>\r\n");
      out.write("  	 				<li><a href=\"#about\">About</a></li>\r\n");
      out.write("  	 				<li><a href=\"#contact\">Contact</a></li>\r\n");
      out.write("  	 				<li><a href=\"./resource/doctorRegistration/doctorRegistration.jsp\">Doctor Registration</a></li>\r\n");
      out.write("  	 				<li><a href=\"#appoinment\">Appoinment</a></li>\r\n");
      out.write("  	 				<li><a href=\"#\">Privacy Policy</a></li>\r\n");
      out.write("  	 			</ul>\r\n");
      out.write("  	 		</div>\r\n");
      out.write("  	 		<div class=\"footer-col\">\r\n");
      out.write("  	 			<h4>Get Help</h4>\r\n");
      out.write("  	 			<ul>\r\n");
      out.write("  	 				<li><a href=\"#\">+94 76 87 55 787</a></li>\r\n");
      out.write("  	 				<li><a href=\"#\">abc@hospital@gmail.com</a></li>\r\n");
      out.write("  	 				<li><a href=\"#\">Patients status</a></li>\r\n");
      out.write("  	 				<li><a href=\"#\">ABC HOSPITAL CLOLOMBO</a></li>\r\n");
      out.write("  	 			</ul>\r\n");
      out.write("  	 		</div>\r\n");
      out.write("  	 		<div class=\"footer-col\">\r\n");
      out.write("  	 			<h4>Address</h4>\r\n");
      out.write("  	 			<ul>\r\n");
      out.write("  	 				<li><a href=\"#\">No . 57 Ritiketiya , new colone , meegama</a></li>\r\n");
      out.write("  	 			</ul>\r\n");
      out.write("  	 		</div>\r\n");
      out.write("  	 		<div class=\"footer-col\">\r\n");
      out.write("  	 			<h4>follow us</h4>\r\n");
      out.write("  	 			<div class=\"social-links\">\r\n");
      out.write("  	 				<a href=\"#\"><i class=\"fa fa-google\"></i></a>\r\n");
      out.write("  	 				<a href=\"#\"><i class=\"fa fa-facebook-f\"></i></a>\r\n");
      out.write("  	 				<a href=\"#\"><i class=\"fa fa-instagram\"></i></a>\r\n");
      out.write("  	 				<a href=\"#\"><i class=\"fa fa-twitter\"></i></a>\r\n");
      out.write("  	 			</div>\r\n");
      out.write("  	 		</div>\r\n");
      out.write("  	 	</div>\r\n");
      out.write("  	 </div>\r\n");
      out.write("  </footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
