/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.10
 * Generated at: 2021-09-30 03:34:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.resource.testimonials;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class testimonial_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./resource/common/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".box-items {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	background: white;\r\n");
      out.write("	border-right: 2px solid black;\r\n");
      out.write("	border-bottom: 2px solid black;\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h4, p {\r\n");
      out.write("	color: black;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("p {\r\n");
      out.write("	color: black;\r\n");
      out.write("	text-align: justify;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h4 {\r\n");
      out.write("	font-weight: bolder;\r\n");
      out.write("	padding: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("p:hover {\r\n");
      out.write("	color: black;\r\n");
      out.write("	text-align: justify;\r\n");
      out.write("	font-size: 25px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h4:hover {\r\n");
      out.write("	font-weight: bolder;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("@media all and (max-width: 300px) {\r\n");
      out.write("	.test h1{\r\n");
      out.write("		font-size:30px;\r\n");
      out.write("		text-align:center;\r\n");
      out.write("		\r\n");
      out.write("		width:100%;\r\n");
      out.write("		height:auto;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media all and (min-width: 300px) {\r\n");
      out.write("	.test h1{\r\n");
      out.write("		font-size:50px;\r\n");
      out.write("		text-align:center;\r\n");
      out.write("		\r\n");
      out.write("		width:100%;\r\n");
      out.write("		height:auto;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container-fluid test\">\r\n");
      out.write("		<div class=\"text-center p-5\">\r\n");
      out.write("			<h1>Customer Testimonials</h1>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"box-item col-sm-12 col-md-4 col-xl-4\">\r\n");
      out.write("				<div>\r\n");
      out.write("					<h4>Mariya Coney</h4>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<p>The room was very clean and sanitary equipment was also\r\n");
      out.write("						provided in the room. The bathrooms also were hygienic.</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"box-items col-sm-12 col-md-8 col-xl-8\">\r\n");
      out.write("				<div>\r\n");
      out.write("					<h4>Powseena Pires</h4>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<p>I wish to appreciate the doctor, sisters, nurses and the\r\n");
      out.write("						other staff for all the services and support that was provided to\r\n");
      out.write("						me (room 108) and my family (room 137) during our stay at the\r\n");
      out.write("						Intermediate Care Centre. From the 4th of June, you all gave us\r\n");
      out.write("						the mental strength to recover from the sickness in our minds and\r\n");
      out.write("						bodies due to COVID-19. Medicine, food and other needs were tended\r\n");
      out.write("						to with care. I look forward to other future patients receiving\r\n");
      out.write("						the same brave service.</p>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"box-items col-sm-12 col-md-8 col-xl-8\">\r\n");
      out.write("				<div>\r\n");
      out.write("					<h4>Powseena Pires</h4>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<p>I wish to appreciate the doctor, sisters, nurses and the\r\n");
      out.write("						other staff for all the services and support that was provided to\r\n");
      out.write("						me (room 108) and my family (room 137) during our stay at the\r\n");
      out.write("						Intermediate Care Centre. From the 4th of June, you all gave us\r\n");
      out.write("						the mental strength to recover from the sickness in our minds and\r\n");
      out.write("						bodies due to COVID-19. Medicine, food and other needs were tended\r\n");
      out.write("						to with care. I look forward to other future patients receiving\r\n");
      out.write("						the same brave service.</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"box-item col-sm-12 col-md-4 col-xl-4\">\r\n");
      out.write("				<div>\r\n");
      out.write("					<h4>Savindu Pasintha</h4>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<p>Cleaning duties are performed properly by the staff. The\r\n");
      out.write("						surroundings are also very relaxing. I saw lots of animals during\r\n");
      out.write("						my stay. The location and weather was also very nice. The staff\r\n");
      out.write("						was very patient. Thank you for caring.</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("	src=\"./resource/common/js/bootstrap.min.js\"></script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
